const images = [
  "/emoji/1.png",
  "/emoji/2.png",
  "/emoji/3.png",
  "/emoji/4.png",
  "/emoji/5.png",
  "/emoji/6.png",
  "/emoji/7.png",
  "/emoji/8.png",
  "/emoji/9.png",
  "/emoji/10.png",
  "/emoji/11.png",
  "/emoji/12.png",
  "/emoji/13.png",
  "/emoji/14.png",
  "/emoji/15.png",
  "/emoji/16.png",
  "/emoji/17.png",
  "/emoji/18.png",
  "/emoji/19.png",
  "/emoji/20.png",
  "/emoji/21.png",
  "/emoji/22.png",
  "/emoji/23.png",
  "/emoji/24.png",
  "/emoji/25.png",
  "/emoji/26.png",
  "/emoji/27.png",
  "/emoji/28.png",
  "/emoji/29.png",
  "/emoji/30.png",
  "/emoji/31.png",
  "/emoji/32.png",
  "/emoji/33.png",
  "/emoji/34.png",
  "/emoji/35.png",
  "/emoji/36.png",
  "/emoji/37.png",
  "/emoji/38.png",
  "/emoji/39.png",
  "/emoji/40.png",
  "/emoji/41.png",
  "/emoji/42.png",
  "/emoji/43.png",
  "/emoji/44.png",
  "/emoji/45.png",
  "/emoji/46.png",
  "/emoji/47.png",
  "/emoji/48.png",
  "/emoji/49.png",
  "/emoji/50.png",
];

export function getRandomImage() {
  let number = Math.floor(Math.random() * images.length);

  return images[number];
}
